// Mocks generated by Mockito 5.4.4 from annotations
// in flower_ecommerce/test/Features/auth/domain/use_cases/register_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_ecommerce/core/common/api_result.dart' as _i2;
import 'package:flower_ecommerce/Features/auth/domain/entities/forget_password_entity.dart'
    as _i6;
import 'package:flower_ecommerce/Features/auth/domain/entities/login_entities.dart'
    as _i9;
import 'package:flower_ecommerce/Features/auth/domain/entities/logout_entity.dart'
    as _i10;
import 'package:flower_ecommerce/Features/auth/domain/entities/register_entities.dart'
    as _i5;
import 'package:flower_ecommerce/Features/auth/domain/entities/reset_password_entity.dart'
    as _i8;
import 'package:flower_ecommerce/Features/auth/domain/entities/verify_password_entity.dart'
    as _i7;
import 'package:flower_ecommerce/Features/auth/domain/repositories/auth_repo.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i3.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.RegisterEntities?>> register(
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? rePassword,
    String? phone,
    String? gender,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            firstName,
            lastName,
            email,
            password,
            rePassword,
            phone,
            gender,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.RegisterEntities?>>.value(
            _FakeResult_0<_i5.RegisterEntities?>(
          this,
          Invocation.method(
            #register,
            [
              firstName,
              lastName,
              email,
              password,
              rePassword,
              phone,
              gender,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.RegisterEntities?>>);

  @override
  _i4.Future<_i2.Result<_i6.ForgetPasswordEntity?>> forgetPassword(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [email],
        ),
        returnValue: _i4.Future<_i2.Result<_i6.ForgetPasswordEntity?>>.value(
            _FakeResult_0<_i6.ForgetPasswordEntity?>(
          this,
          Invocation.method(
            #forgetPassword,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i6.ForgetPasswordEntity?>>);

  @override
  _i4.Future<_i2.Result<_i7.VerifyPasswordEntity?>> verifyPassword(
          String? otp) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPassword,
          [otp],
        ),
        returnValue: _i4.Future<_i2.Result<_i7.VerifyPasswordEntity?>>.value(
            _FakeResult_0<_i7.VerifyPasswordEntity?>(
          this,
          Invocation.method(
            #verifyPassword,
            [otp],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i7.VerifyPasswordEntity?>>);

  @override
  _i4.Future<_i2.Result<_i8.ResetPasswordEntity?>> resetPassword(
    String? email,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [
            email,
            newPassword,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<_i8.ResetPasswordEntity?>>.value(
            _FakeResult_0<_i8.ResetPasswordEntity?>(
          this,
          Invocation.method(
            #resetPassword,
            [
              email,
              newPassword,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i8.ResetPasswordEntity?>>);

  @override
  _i4.Future<_i2.Result<_i9.LoginEntitie>> login(
    String? name,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            name,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<_i9.LoginEntitie>>.value(
            _FakeResult_0<_i9.LoginEntitie>(
          this,
          Invocation.method(
            #login,
            [
              name,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i9.LoginEntitie>>);

  @override
  _i4.Future<_i2.Result<_i10.LogoutEntity>> logout(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [token],
        ),
        returnValue: _i4.Future<_i2.Result<_i10.LogoutEntity>>.value(
            _FakeResult_0<_i10.LogoutEntity>(
          this,
          Invocation.method(
            #logout,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i10.LogoutEntity>>);
}
