include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_function_literals_in_foreach_calls: ignore
    avoid_print: ignore
    omit_local_variable_types: ignore
    overridden_fields: ignore
    prefer_collection_literals: ignore
    unnecessary_await_in_return: ignore
    unnecessary_this: ignore
    use_setters_to_change_properties: ignore
  exclude:
    - localization/**
