// Mocks generated by Mockito 5.4.4 from annotations
// in flower_ecommerce/test/Features/auth/data/repositories/login_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_ecommerce/core/common/api_result.dart' as _i2;
import 'package:flower_ecommerce/Features/auth/data/data_sources/auth_online_datasource.dart'
    as _i3;
import 'package:flower_ecommerce/Features/auth/data/models/request/forget_password_request/reset_password_request.dart'
    as _i10;
import 'package:flower_ecommerce/Features/auth/data/models/request/login_model_dto.dart'
    as _i12;
import 'package:flower_ecommerce/Features/auth/data/models/request/register_model_dto.dart'
    as _i6;
import 'package:flower_ecommerce/Features/auth/domain/entities/forget_password_entity.dart'
    as _i7;
import 'package:flower_ecommerce/Features/auth/domain/entities/login_entities.dart'
    as _i11;
import 'package:flower_ecommerce/Features/auth/domain/entities/logout_entity.dart'
    as _i13;
import 'package:flower_ecommerce/Features/auth/domain/entities/register_entities.dart'
    as _i5;
import 'package:flower_ecommerce/Features/auth/domain/entities/reset_password_entity.dart'
    as _i9;
import 'package:flower_ecommerce/Features/auth/domain/entities/verify_password_entity.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthOnLineDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthOnLineDataSource extends _i1.Mock
    implements _i3.AuthOnLineDataSource {
  MockAuthOnLineDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.RegisterEntities?>> register(
          _i6.RegisterModelDto? registerModelDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [registerModelDto],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.RegisterEntities?>>.value(
            _FakeResult_0<_i5.RegisterEntities?>(
          this,
          Invocation.method(
            #register,
            [registerModelDto],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.RegisterEntities?>>);

  @override
  _i4.Future<_i2.Result<_i7.ForgetPasswordEntity?>> forgetPassword(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [email],
        ),
        returnValue: _i4.Future<_i2.Result<_i7.ForgetPasswordEntity?>>.value(
            _FakeResult_0<_i7.ForgetPasswordEntity?>(
          this,
          Invocation.method(
            #forgetPassword,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i7.ForgetPasswordEntity?>>);

  @override
  _i4.Future<_i2.Result<_i8.VerifyPasswordEntity?>> verifyPassword(
          String? otp) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPassword,
          [otp],
        ),
        returnValue: _i4.Future<_i2.Result<_i8.VerifyPasswordEntity?>>.value(
            _FakeResult_0<_i8.VerifyPasswordEntity?>(
          this,
          Invocation.method(
            #verifyPassword,
            [otp],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i8.VerifyPasswordEntity?>>);

  @override
  _i4.Future<_i2.Result<_i9.ResetPasswordEntity?>> resetPassword(
          _i10.ResetPasswordRequest? resetPasswordRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [resetPasswordRequest],
        ),
        returnValue: _i4.Future<_i2.Result<_i9.ResetPasswordEntity?>>.value(
            _FakeResult_0<_i9.ResetPasswordEntity?>(
          this,
          Invocation.method(
            #resetPassword,
            [resetPasswordRequest],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i9.ResetPasswordEntity?>>);

  @override
  _i4.Future<_i2.Result<_i11.LoginEntitie>> login(
          _i12.LoginModelDto? loginModelDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginModelDto],
        ),
        returnValue: _i4.Future<_i2.Result<_i11.LoginEntitie>>.value(
            _FakeResult_0<_i11.LoginEntitie>(
          this,
          Invocation.method(
            #login,
            [loginModelDto],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i11.LoginEntitie>>);

  @override
  _i4.Future<_i2.Result<_i13.LogoutEntity>> logout(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [token],
        ),
        returnValue: _i4.Future<_i2.Result<_i13.LogoutEntity>>.value(
            _FakeResult_0<_i13.LogoutEntity>(
          this,
          Invocation.method(
            #logout,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i13.LogoutEntity>>);
}
