// Mocks generated by Mockito 5.4.4 from annotations
// in flower_ecommerce/test/Features/notifications_list/data/repositories/notifications_list_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_ecommerce/core/common/api_result.dart' as _i2;
import 'package:flower_ecommerce/Features/notifications_list/data/data_sources/online_data_source/notifications_list_online_data_source.dart'
    as _i3;
import 'package:flower_ecommerce/Features/notifications_list/domain/entities/notifications_list_entity.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotificationsListOnlineDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsListOnlineDataSource extends _i1.Mock
    implements _i3.NotificationsListOnlineDataSource {
  MockNotificationsListOnlineDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.NotificationsListEntity>> getAllNotifications(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllNotifications,
          [token],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.NotificationsListEntity>>.value(
            _FakeResult_0<_i5.NotificationsListEntity>(
          this,
          Invocation.method(
            #getAllNotifications,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.NotificationsListEntity>>);
}
