// Mocks generated by Mockito 5.4.4 from annotations
// in flower_ecommerce/test/Features/edit_profile/data/repo_impl/edit_profile_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_ecommerce/core/common/api_result.dart' as _i2;
import 'package:flower_ecommerce/Features/edit_profile/data/data_source/edit_profile_data_source.dart'
    as _i3;
import 'package:flower_ecommerce/Features/edit_profile/domain/entities/edit_profile_entity.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EditProfileDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileDataSource extends _i1.Mock
    implements _i3.EditProfileDataSource {
  MockEditProfileDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.EditProfileEntity>> editProfile(
    String? token,
    String? firstName,
    String? lastName,
    String? email,
    String? phone,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [
            token,
            firstName,
            lastName,
            email,
            phone,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.EditProfileEntity>>.value(
            _FakeResult_0<_i5.EditProfileEntity>(
          this,
          Invocation.method(
            #editProfile,
            [
              token,
              firstName,
              lastName,
              email,
              phone,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.EditProfileEntity>>);
}
