// Mocks generated by Mockito 5.4.4 from annotations
// in flower_ecommerce/test/Features/best_seller/presentation/best_seller_view_model/best_seller_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_ecommerce/core/common/api_result.dart' as _i3;
import 'package:flower_ecommerce/Features/best_seller/domain/entities/best_seller_entity.dart'
    as _i6;
import 'package:flower_ecommerce/Features/best_seller/domain/repositories/best_repo.dart'
    as _i2;
import 'package:flower_ecommerce/Features/best_seller/domain/use_case/best_seller_use_case.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBestRepo_0 extends _i1.SmartFake implements _i2.BestRepo {
  _FakeBestRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_1<T> extends _i1.SmartFake implements _i3.Result<T> {
  _FakeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BestSellerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBestSellerUseCase extends _i1.Mock implements _i4.BestSellerUseCase {
  MockBestSellerUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BestRepo get bestRepo => (super.noSuchMethod(
        Invocation.getter(#bestRepo),
        returnValue: _FakeBestRepo_0(
          this,
          Invocation.getter(#bestRepo),
        ),
      ) as _i2.BestRepo);

  @override
  set bestRepo(_i2.BestRepo? _bestRepo) => super.noSuchMethod(
        Invocation.setter(
          #bestRepo,
          _bestRepo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.Result<List<_i6.BestSellerEntity>?>> invoke() =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<_i6.BestSellerEntity>?>>.value(
            _FakeResult_1<List<_i6.BestSellerEntity>?>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<_i6.BestSellerEntity>?>>);
}
